version: '3.4'

services:
  deliveryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "56020:80"
    depends_on:
      - mongo
  mongo:
    ports:
      - "27018:27017"
