version: '3.4'

services:
  deliveryservice.api:
    image: ${DOCKER_REGISTRY-}deliveryserviceapi
    build:
      context: .
      dockerfile: DeliveryService.Api/Dockerfile
  mongo:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    image: mongo
